services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./OrderServiceA2/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - product-service
      - order-service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus

  product-service:
    build: ./ProductServiceA2
    image: product-service:blue
    ports:
      - "8080:8080"
    environment:
      ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
    depends_on:
      - zipkin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  order-service:
    build: ./OrderServiceA2
    image: order-service:blue
    ports:
      - "8081:8081"
    environment:
      PRODUCT_SERVICE_URL: "http://product-service:8080"
      ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
    depends_on:
      zipkin:
        condition: service_started
      product-service:
        condition: service_healthy # use `docker events --filter 'event=health_status'` to see the logs for Healthchecks

