{
 "title": "E-Commerce Services Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (jvm_memory_used_bytes{area=\"heap\",job=~\"order-service|product-service\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count{job=~\"order-service|product-service\",uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Order Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "total_orders_total", "legendFormat": "{{job}} total_orders" }
   ]
  },
  {
   "title": "Pod CPU / Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by (job, instance) (process_cpu_usage{job=~\"order-service|product-service\"}) * 100",
     "legendFormat": "{{job}} CPU"
    },
    {
     "expr": "avg by (job, instance) (process_resident_memory_bytes{job=~\"order-service|product-service\"})",
     "legendFormat": "{{job}} RSS"
    }
   ]
  }
 ]
}