apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: assignment-3
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      version: blue
  template:
    metadata:
      labels:
        app: order-service
        version: blue
    spec:
      containers:
        - name: order-service
          image: order-service:blue
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: APP_VERSION
              value: "v1.0"
          envFrom:
            - configMapRef:
                name: assignment-3-config