spring.application.name=ProductService

server.port=8080

spring.datasource.driver-class-name=org.h2.Driver

# Logging pattern
logging.pattern.console=%d{HH:mm:ss} %-5level [%X{correlationId}] [%X{traceId}] %logger{36} - %msg%n